SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE users RESTART IDENTITY;
TRUNCATE TABLE question RESTART IDENTITY;
TRUNCATE TABLE answer RESTART IDENTITY;
TRUNCATE TABLE delete_history RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;